config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  devise_for :users

  resources :tasks do
    member do
      post :share
      put  :done
    end
  end

  get 'refresh_activities' => 'tasks#refresh_activities'
end

app/models/task.rb
class Task < ActiveRecord::Base
  include PublicActivity::Model

  has_and_belongs_to_many :users
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :tasks

  def create_task_count
    Task.where(user_id: id).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # def owner_or_worker(task)
  #   task.users.include?(current_user) || current_user == task.owner
  # end
  helper_method :bootstrap_class_for

  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, except: [:index, :create, :new, :refresh_activities]
  before_action :check_permissions!, except: [:show, :index, :create, :new, :refresh_activities]
  before_action :load_activities, only: [:index, :show, :new, :edit, :refresh_activities]

  def index
    @tasks = Task.includes(:users, :creator).where(user_id: current_user.id) + current_user.tasks.includes(:users)
    @tasks.sort_by!(&:updated_at).reverse!
    @task = Task.new
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.creator = current_user
    if @task.save
      redirect_to @task
      flash[:success] = 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task
      flash[:success] = 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url
    flash[:success] = "Task was successfully destroyed."
  end

  def share
    @user = User.find_by(email: params[:share][:email])
    if @user
      if @task.users.include?(@user)
        redirect_to @task
        flash[:error] = 'User already have that task'
      else
        @task.create_activity :share, recipient: @user, owner: current_user
        @task.users << @user
        redirect_to @task, notice: 'Task was successfully shared.'
      end
    else
      redirect_to @task
      flash[:error] = "Sorry, did not find any user with email: #{params[:share][:email]}"
    end
  end

  def done
    @task.update(done: true)
    redirect_to root_path
    flash[:success] = 'Task was marked as completed'
  end

  def refresh_activities
    @tasks = Task.includes(:users, :creator).where(user_id: current_user.id) + current_user.tasks.includes(:users)
    @tasks.sort_by!(&:updated_at).reverse!
    respond_to do |format|
      format.js {}
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :done, :user_id, user_ids: [])
  end

  def check_permissions!
    unless @task.users.include?(current_user) || @task.creator == current_user
      redirect_to root_path
      flash[:error] = 'You do not have privileges for this action.'
    end
  end

  def load_activities
    @activities = PublicActivity::Activity.order('created_at DESC')
                                          .where(recipient_id: current_user.id, recipient_type: 'User')
                                          .includes(:owner, :trackable)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_activities.html.haml
%ul.list-group#feed
  - @activities.each do |activity|
    %li.list-group-item
      %span{:class => "glyphicon glyphicon-#{activity.key.match(/\.(.*)/)[1]}"}
      %small.text-muted= activity.created_at.strftime('%H:%M:%S %-d %B %Y')
      %br/
      %strong= activity.owner ? activity.owner.email : 'Guest'
      = render_activity(activity, display: :i18n)
      - if activity.trackable
        = link_to activity.trackable.title, task_path(activity.trackable), class: 'label label-info'
      - elsif activity.title
        %span.text-muted
        = activity.title
      - else
        with unknown title.

app/views/layouts/_flash_messages.html.haml
.container
  - flash.each do |type, message|
    %div{:class => "alert #{bootstrap_class_for(type)} alert-dismissable fade in"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = message

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand{ style: "font-weight: 600;" }
        = link_to 'TaskManager', root_path
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'All Tasks', tasks_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              = "Logged as #{current_user.name || current_user.email}"
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Edit profile", edit_user_registration_path
              %li.divider
              %li= link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Login", new_user_session_path
          %li= link_to "Sign up", new_user_registration_path

app/views/layouts/_stats.html.haml
.card
  = image_tag('avatar.jpg', size: '250x250')
  .card-block
    %h4.card-title.text-center
      = current_user.email
  %ul.list-group.list-group-flush
    %li.list-group-item
      Tasks created:
      %b= current_user.create_task_count
    %li.list-group-item#delegated
      Tasks delegated from others:
      %b= current_user.tasks.count

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Meals
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container
      = yield

app/views/tasks/_form.html.haml
= simple_form_for(@task) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    - if @task.id
      = f.input :done

  .form-actions
    = f.button :submit, class: 'btn btn-primary btn-block'

app/views/tasks/_task.html.haml
- @tasks.each  do |task|
  .panel{class: "panel-#{task.done? ? 'success' : 'warning'}"}
    .panel-heading
      %h4
        = task.title
        - if task.users.include?(current_user)
          %span.label.label-warning subscription
        - elsif current_user == task.creator
          %span.label.label-primary creator
        %small.pull-right
          Updated
          = "#{time_ago_in_words(task.updated_at)} ago"
    .panel-body
      %p= task.description
    .panel-heading
      = link_to 'Show', task_path(task), class: "btn btn-default"
      - if task.users.include?(current_user) || current_user == task.creator
        = link_to 'Destroy', task, method: :delete, class: "btn btn-default", data: { confirm: "Are u sure?" }

app/views/tasks/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1 Editing task

    = render 'form'

    = link_to 'Show', @task
    \|
    = link_to 'Back', tasks_path

app/views/tasks/index.html.haml
.row
  .col-md-3
    = render 'layouts/stats'
    %hr/
    - if user_signed_in?
      %h2.text-center
        %b Create new task

      = render 'tasks/form'

  .col-md-6#tasklist
    - if @tasks.empty?
      There are no tasks yet!
    - else
      / = render @tasks

      = render 'task'

  .col-md-3
    = render 'layouts/activities'

app/views/tasks/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1 New task

    = render 'form'

    = link_to 'Back', tasks_path

app/views/tasks/refresh_activities.js.erb
$('ul.list-group#feed').html("<%= escape_javascript(render partial: 'layouts/activities') %>");
$('#tasklist').html("<%= escape_javascript(render partial: 'task') %>");
$('#delegated b').html("<%= current_user.tasks.count %>");

app/views/tasks/show.html.haml
.row
  .col-md-6
    %blockquote
      %h1= @task.title
      %p= @task.description
      %footer
        owner:
        = @task.creator.email
      - unless @task.users.blank?
        %footer
          workers:
          = @task.users.map(&:email).to_sentence
      %br/
      = link_to 'Back', tasks_path, class: 'btn btn-default'
      - if @task.users.include?(current_user) || current_user == @task.creator
        - unless @task.done
          = link_to 'Complete', done_task_path(@task), method: :put, class: 'btn btn-default'
        = link_to 'Edit', edit_task_path(@task), class: 'btn btn-default'
        = link_to 'Destroy', @task, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are u sure?' }
  .col-md-3
    - if @task.users.include?(current_user) || current_user == @task.creator
      = simple_form_for :share, :url => share_task_path, :method => :post do |f|
        = f.input :email, label: false, placeholder: 'Enter user email'
        = f.button :submit, 'Share this task with user', class: 'btn btn-primary btn-block'
  .col-md-3
    = render 'layouts/activities'